blank_issues_enabled: false
contact_links:
  - name: Comments, questions and opinions
    url: https://github.com/zSimone35/TypogNotes/discussions
    about: For general feedback or a question, use Discussions.
