blank_issues_enabled: false
contact_links:
  - name: Commenti, domande e opinioni
    url: https://github.com/zSimone35/TypogNotes/discussions
    about: Per un parere generale o una domanda usa le Discussioni.
