name: Suggest an idea
description: A new feature or an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: perche
    attributes:
      label: Why would it be useful to you?
